package com.example.service

import java.util.Locale

data class LinuxCncMachineConfig(
    val machineName: String = "LinuxCNC-4Axis-Mill",
    val coordinates: String = "X Y Z A",
    val linearUnits: String = "mm",
    val kinematicsType: String = "trivkins",
    val maxLinearVelocity: Double = 150.0,
    val maxLinearAcceleration: Double = 1200.0,
    val xMinLimit: Double = -50.0,
    val xMaxLimit: Double = 550.0,
    val xStepScale: Double = 80.0,
    val yMinLimit: Double = -30.0,
    val yMaxLimit: Double = 400.0,
    val yStepScale: Double = 80.0,
    val zMinLimit: Double = -220.0,
    val zMaxLimit: Double = 15.0,
    val zStepScale: Double = 400.0,
    val aMinLimit: Double = -9999.0,
    val aMaxLimit: Double = 9999.0,
    val aStepScale: Double = 8.888,
    val spindleMinRpm: Double = 100.0,
    val spindleMaxRpm: Double = 24000.0,
    val spindleScale: Double = 1.0,
    val rawSections: Map<String, Map<String, String>> = emptyMap()
)

object LinuxCncIniParser {

    fun generateSampleIni(): String = exportDefaultIni()

    fun parseIni(content: String): LinuxCncMachineConfig {
        val sections = mutableMapOf<String, MutableMap<String, String>>()
        var currentSection = "DEFAULT"

        content.lines().forEach { rawLine ->
            val line = rawLine.trim()
            if (line.isEmpty() || line.startsWith("#") || line.startsWith(";")) return@forEach

            if (line.startsWith("[") && line.endsWith("]")) {
                currentSection = line.substring(1, line.length - 1).trim().uppercase(Locale.ROOT)
                if (!sections.containsKey(currentSection)) {
                    sections[currentSection] = mutableMapOf()
                }
            } else if (line.contains("=")) {
                val parts = line.split("=", limit = 2)
                val key = parts[0].trim().uppercase(Locale.ROOT)
                // Remove inline comments
                val valueRaw = parts[1].split("#", ";", limit = 2)[0].trim()
                sections.getOrPut(currentSection) { mutableMapOf() }[key] = valueRaw
            }
        }

        val emcSec = sections["EMC"] ?: emptyMap()
        val trajSec = sections["TRAJ"] ?: emptyMap()
        val kinSec = sections["KINEMATICS"] ?: emptyMap()
        val axisX = sections["AXIS_X"] ?: sections["JOINT_0"] ?: emptyMap()
        val joint0 = sections["JOINT_0"] ?: emptyMap()
        val axisY = sections["AXIS_Y"] ?: sections["JOINT_1"] ?: emptyMap()
        val joint1 = sections["JOINT_1"] ?: emptyMap()
        val axisZ = sections["AXIS_Z"] ?: sections["JOINT_2"] ?: emptyMap()
        val joint2 = sections["JOINT_2"] ?: emptyMap()
        val axisA = sections["AXIS_A"] ?: sections["JOINT_3"] ?: emptyMap()
        val joint3 = sections["JOINT_3"] ?: emptyMap()
        val spindleSec = sections["SPINDLE_0"] ?: sections["SPINDLE"] ?: emptyMap()

        return LinuxCncMachineConfig(
            machineName = emcSec["MACHINE"] ?: "LinuxCNC Machine",
            coordinates = trajSec["COORDINATES"] ?: "X Y Z",
            linearUnits = trajSec["LINEAR_UNITS"] ?: "mm",
            kinematicsType = kinSec["KINEMATICS"] ?: "trivkins",
            maxLinearVelocity = trajSec["MAX_LINEAR_VELOCITY"]?.toDoubleOrNull() ?: 150.0,
            maxLinearAcceleration = trajSec["MAX_LINEAR_ACCELERATION"]?.toDoubleOrNull() ?: 1200.0,
            xMinLimit = axisX["MIN_LIMIT"]?.toDoubleOrNull() ?: -50.0,
            xMaxLimit = axisX["MAX_LIMIT"]?.toDoubleOrNull() ?: 550.0,
            xStepScale = (axisX["SCALE"] ?: joint0["SCALE"])?.toDoubleOrNull() ?: 80.0,
            yMinLimit = axisY["MIN_LIMIT"]?.toDoubleOrNull() ?: -30.0,
            yMaxLimit = axisY["MAX_LIMIT"]?.toDoubleOrNull() ?: 400.0,
            yStepScale = (axisY["SCALE"] ?: joint1["SCALE"])?.toDoubleOrNull() ?: 80.0,
            zMinLimit = axisZ["MIN_LIMIT"]?.toDoubleOrNull() ?: -220.0,
            zMaxLimit = axisZ["MAX_LIMIT"]?.toDoubleOrNull() ?: 15.0,
            zStepScale = (axisZ["SCALE"] ?: joint2["SCALE"])?.toDoubleOrNull() ?: 400.0,
            aMinLimit = axisA["MIN_LIMIT"]?.toDoubleOrNull() ?: -9999.0,
            aMaxLimit = axisA["MAX_LIMIT"]?.toDoubleOrNull() ?: 9999.0,
            aStepScale = (axisA["SCALE"] ?: joint3["SCALE"])?.toDoubleOrNull() ?: 8.888,
            spindleMinRpm = spindleSec["MIN_FORWARD_VELOCITY"]?.toDoubleOrNull() ?: 100.0,
            spindleMaxRpm = spindleSec["MAX_FORWARD_VELOCITY"]?.toDoubleOrNull() ?: 24000.0,
            spindleScale = spindleSec["SCALE"]?.toDoubleOrNull() ?: 1.0,
            rawSections = sections
        )
    }

    fun exportDefaultIni(): String {
        return """
            # ==============================================================================
            # LinuxCNC Machine Configuration File (machine.ini)
            # Generated by LinuxCncDroid Mobile Pendant
            # ==============================================================================
            
            [EMC]
            MACHINE = LinuxCNC-Mill-4Axis
            DEBUG = 0
            VERSION = 1.1

            [DISPLAY]
            DISPLAY = axis
            CYCLE_TIME = 0.100
            HELP_FILE = doc/help.txt
            POSITION_OFFSET = RELATIVE
            POSITION_FEEDBACK = ACTUAL
            MAX_FEED_OVERRIDE = 1.5
            MAX_SPINDLE_OVERRIDE = 1.5
            DEFAULT_SPINDLE_SPEED = 6000
            INTRO_GRAPHIC = linuxcnc.gif
            INTRO_TIME = 2

            [FILTER]
            PROGRAM_EXTENSION = .png,.gif,.jpg Greyscale Depth Image
            PROGRAM_EXTENSION = .py Python Script
            png = image-to-gcode
            gif = image-to-gcode
            jpg = image-to-gcode
            py = python

            [RS274NGC]
            PARAMETER_FILE = linuxcnc.var
            SUBROUTINE_PATH = ../macros
            USER_M_PATH = ../m_codes

            [EMCMOT]
            EMCMOT = motmod
            COMM_TIMEOUT = 1.0
            BASE_PERIOD = 0
            SERVO_PERIOD = 1000000

            [TASK]
            TASK = milltask
            CYCLE_TIME = 0.010

            [HAL]
            HALUI = halui
            HALFILE = core_stepper.hal

            [TRAJ]
            COORDINATES = X Y Z A
            LINEAR_UNITS = mm
            ANGULAR_UNITS = deg
            DEFAULT_LINEAR_VELOCITY = 25.0
            MAX_LINEAR_VELOCITY = 150.0
            DEFAULT_LINEAR_ACCELERATION = 500.0
            MAX_LINEAR_ACCELERATION = 1200.0
            NO_FORCE_HOMING = 0

            [AXIS_X]
            MIN_LIMIT = -50.0
            MAX_LIMIT = 550.0
            MAX_VELOCITY = 150.0
            MAX_ACCELERATION = 1200.0

            [JOINT_0]
            TYPE = LINEAR
            HOME = 0.0
            MIN_LIMIT = -50.0
            MAX_LIMIT = 550.0
            MAX_VELOCITY = 150.0
            MAX_ACCELERATION = 1200.0
            STEPGEN_MAXACCEL = 1500.0
            SCALE = 160.0
            FERROR = 1
            MIN_FERROR = 0.25
            HOME_OFFSET = -50.0
            HOME_SEARCH_VEL = -20.0
            HOME_LATCH_VEL = 1.0
            HOME_SEQUENCE = 1

            [AXIS_Y]
            MIN_LIMIT = -30.0
            MAX_LIMIT = 400.0
            MAX_VELOCITY = 150.0
            MAX_ACCELERATION = 1200.0

            [JOINT_1]
            TYPE = LINEAR
            HOME = 0.0
            MIN_LIMIT = -30.0
            MAX_LIMIT = 400.0
            MAX_VELOCITY = 150.0
            MAX_ACCELERATION = 1200.0
            STEPGEN_MAXACCEL = 1500.0
            SCALE = 160.0
            FERROR = 1
            MIN_FERROR = 0.25
            HOME_OFFSET = -30.0
            HOME_SEARCH_VEL = -20.0
            HOME_LATCH_VEL = 1.0
            HOME_SEQUENCE = 2

            [AXIS_Z]
            MIN_LIMIT = -220.0
            MAX_LIMIT = 15.0
            MAX_VELOCITY = 80.0
            MAX_ACCELERATION = 800.0

            [JOINT_2]
            TYPE = LINEAR
            HOME = 0.0
            MIN_LIMIT = -220.0
            MAX_LIMIT = 15.0
            MAX_VELOCITY = 80.0
            MAX_ACCELERATION = 800.0
            STEPGEN_MAXACCEL = 1000.0
            SCALE = 160.0
            FERROR = 1
            MIN_FERROR = 0.25
            HOME_OFFSET = 15.0
            HOME_SEARCH_VEL = 15.0
            HOME_LATCH_VEL = -1.0
            HOME_SEQUENCE = 0

            [AXIS_A]
            MIN_LIMIT = -9999.0
            MAX_LIMIT = 9999.0
            MAX_VELOCITY = 360.0
            MAX_ACCELERATION = 2400.0

            [JOINT_3]
            TYPE = ANGULAR
            HOME = 0.0
            SCALE = 88.888
            HOME_SEQUENCE = 3
        """.trimIndent()
    }
}
